name: Build and Publish Packages

on:
  push:
    branches:
      - master

env:
  GRADLE_OPTS: -Dorg.gradle.console=plain

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up JDK
        uses: actions/setup-java@v2
        with:
          java-version: '11'

      - name: Build with Gradle
        run: ./gradlew build

      - name: Publish to GitHub Packages
        run: |
          echo "//registry.gradle.org/api/login" >> ~/.gradle/gradle.properties
          echo "registry=https://maven.pkg.github.com/akshay987" >> ~/.gradle/gradle.properties
          ./gradlew publish
